### ISSUE TITLE
Which dictionary does the pretrained model use?

### ISSUE THREAD

**Issue by sophiefy** [6gsn/marine#21]
Hi, thanks for sharing such a great work! 

As shown in your paper, unidic is used in pre-processing. But the README in this repo says the provided model is not the same as the one in your paper. And I notice that the provided model can work with OpenJTalk, which is based on naist-jdic.

 So I wonder which dictionary the provided model uses?

**Comment by 6gsn** [comment]
Hi, @sophiefy!

Sorry for my late response and your confusion.

As you pointed, we used Unidic-CSJ for extracting linguistic features in our paper. Also, in this repository, we used OpenJTalk-dic (≒ naist-jdic) provided [pyopenjtalk](https://github.com/r9y9/pyopenjtalk) for the training of released model 👍

**Comment by sophiefy** [comment]
Thanks for your kind reply!
